version: '3'

services:
  ride-sharing-service:
    build: ./ride_sharing_service/
    depends_on:
      - communication_service
    restart: always
    
  rating-service:
    build: ./rating/
    restart: always
    depends_on: 
      - mongodb_container

  communication_service:
    build: ./communication/
    ports: 
      - 5003:5000
    restart: always
    
  nginx:
    build: ./nginx/
    ports:
      - 80:80
    depends_on:
      - ride-sharing-service
      - rating-service
    restart: always


  mongodb_container:
    image: mongo:latest
    ports:
      - 2717:27017
    volumes:
      - mongodb_data_container:/data/db
    restart: always

volumes:
  mongodb_data_container: